# Generated by Django 5.1.4 on 2025-01-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_rental_rental_date_alter_rental_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_year',
            field=models.CharField(max_length=100),
        ),
    ]
